### ISSUE TITLE
how to use it in a bootstrap menu ?

### ISSUE THREAD

**Issue by kermorgant** [rollerworks/NavigationBundle#11]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Hello,

I'd like to use this bundle, as I need to put the menu structure of my app outside of the code, but I also need to tweak the template to make a bootstrap compatible menu.

The way I use to do it is by [using a specific template for knp menu](https://gist.github.com/nateevans/9958390), but this requires some attributes on the "ul" elements (class='nav navbar-nav' by example)

In the current situation, I can add options like this on the "li" items but not on the "ul" :+1: 
`

                    options:
                        attributes:
                            class: 'nav navbar-nav dropdown-toggle'

`

I don't know if this needs some modification of this bundle or if there's a way to get it another way ?

Regards
Mikael

**Comment by sstok** [comment]
To be clear you want to do this on the menu root or a child-node?

Configuring the menu root is not possible at the moment (can be fixed 👍 ) to configure a child-node apply the options for the node that that defines the items.

**Comment by kermorgant** [comment]
Thanks for getting back !

It was meant to be on the root node, so you confirm what I suspected. For the moment, I took another similar bundle to achieve that.

**Comment by sstok** [comment]
Which bundle are you using now?

**Comment by kermorgant** [comment]
Found this one to be sf3 compatible : jbouzekri/config-knp-menu-bundle
It should map every knp attribute
